name: Post Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # Executa a cada 30 minutos
  workflow_dispatch:        # Permite execução manual

jobs:
  tweet_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Restaura o cache do arquivo last_posted.json
      - name: Restore last_posted.json cache
        uses: actions/cache@v3
        with:
          path: last_posted.json
          key: last-posted-cache

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy

      - name: Run tweet script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python main.py

      # Salva o cache do arquivo last_posted.json
      - name: Cache last_posted.json
        uses: actions/cache@v3
        with:
          path: last_posted.json
          key: last-posted-cache
