name: Post Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # Executa a cada 30 minutos
  workflow_dispatch:        # Permite execução manual

jobs:
  tweet_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true  # Permite commit com credenciais do GitHub Actions

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy

      - name: Run tweet script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python main.py

      # Commit e push do arquivo last_posted.json atualizado no repositório
      - name: Commit last_posted.json
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add last_posted.json
          git commit -m "Atualiza last_posted.json com novos links postados" || echo "Nenhuma alteração para commit"
          git push
